name: Build APK and Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npm install @capacitor/cli
          npx cap sync

      - name: Setup Java and Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload to Google Drive
        uses: Jodebu/upload-google-drive-action@v1
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          source: android/app/build/outputs/apk/release/app-release.apk
          name: snipersol.apk
